name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend:
    name: Backend · lint & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: backend/go.sum

      - name: Resolve dependencies
        run: go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -ldflags="-s -w" -o /tmp/vilavest ./cmd/api

      - name: Test
        run: go test ./... -count=1

  frontend:
    name: Frontend · lint & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: https://api-dev.vilavest.leonardoflores.dev.br/api/v1
